version: '3'
services:
  php-fpm:
    build: ./docker/php
    image: enghaw/enghaw-api:php-fpm
    restart: on-failure
    container_name: enghaw-api-php-fpm
    command: php-fpm
    links:
        - elasticsearch
    volumes:
      - ./:/enghaw-api
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 9000 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2

  nginx:
    build: ./docker/nginx
    image: enghaw/enghaw-api:nginx
    restart: on-failure
    container_name: enghaw-api-nginx
    command: nginx -g "daemon off;"
    links:
      - php-fpm
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    volumes:
      - ./:/enghaw-api
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 80 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2
    
  elasticsearch:
    build: ./docker/elasticsearch
    image: enghaw/enghaw-api:elasticsearch
    container_name: enghaw-api-elasticsearch
    environment:
      - cluster.name=enghaw
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./docker/elasticsearch/esdatadir:/usr/share/elasticsearch/data